export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_DAY = 'CHANGE_DAY';
export const CHANGE_CURRENT_CONDITIONS = 'CHANGE_CURRENT_CONDITIONS';
export const CHANGE_DAILY_CONDITIONS = 'CHANGE_DAILY_CONDITIONS';
export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
